pipeline{
    agent none
    stages{
        stage('Build') {
            agent {
                docker{
                    image 'python:2-alpine'
                    label 'my-defined-label'
                    args  '-v /tmp:/tmp'
                }
            }
            steps{
            sh 'python -m py_cpmpile sources/add2vals.py sources/calc.py'
            }
        }
    }
}
