pipeline{
    agent none
    stages{
        stage('Build') {
            agent {
                docker {
                    image 'python:3-alpine'
                }
            }
            steps{
            sh 'python -m py_cpmpile sources/add2vals.py sources/calc.py'
            }
        }
    }
}
